os:
  - linux
language: c
sudo: false
addons:
  apt:
    packages:
    - libgc-dev
    - libgmp-dev
before_install:
  - date
  - cat /proc/cpuinfo
  - cd ${HOME}
  - gcc --version
  - git clone https://github.com/githwxi/ATS-Postiats.git
  # Setting up
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.12
  - export ATSHOMERELOC=ATS-0.2.12
  - export PATSHOME=${HOME}/ATS-Postiats
  - export PATH=${PATSHOME}/bin:${PATH}
  # Build ATS1
  - ${HOME}/ATS-Postiats/travis-ci/ats1_setup.sh 0.2.12
  - cd ${ATSHOME} && ./configure && make all_ngc
  # Build ATS2
  - cd ${PATSHOME} && make -f codegen/Makefile_atslib && make -f Makefile_devl src_depend && make -f Makefile_devl all
  - patsopt --version
script:
  - cd ${TRAVIS_BUILD_DIR}
  - make
after_script:
  - date
